<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>false</UseWindowsForms>
    <UseAspNetCore>false</UseAspNetCore>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="&quot;E:\DevSpace\etc\인증서\CodeSign\codesign.bat&quot; $(TargetPath) $(ConfigurationName)" />
  </Target>

</Project>
