<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AssemblyName>HxCore.Web.NC.v1.0</AssemblyName>
    <RootNamespace>HxCore.Web</RootNamespace>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.2</AssemblyVersion>
    <FileVersion>1.0.1.2</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.6" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HxCoreData\HxCoreData.csproj" />
    <ProjectReference Include="..\HxCore\HxCore.csproj" />
  </ItemGroup>

</Project>
