<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>HxCore.Standard.DE</RootNamespace>
    <AssemblyName>HxCore.Standard.DE.v1.0</AssemblyName>
    <Authors>TypeSW</Authors>
    <Company>TypeSW</Company>
    <Product>HxCore</Product>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Document.Processor" Version="22.2.14">
      <GeneratePathProperty></GeneratePathProperty>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="PDFsharpNetStandard2" Version="1.51.4845" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HxCore\HxCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="NETStandard.Library">
      <GeneratePathProperty></GeneratePathProperty>
    </PackageReference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="&quot;E:\DevSpace\etc\인증서\CodeSign\codesign.bat&quot; $(TargetPath)" />
  </Target>

</Project>
