<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>HxCore.Standard.v1.4</AssemblyName>
    <RootNamespace>HxCore</RootNamespace>
    <Company>TypeSW</Company>
    <Product>HxCore</Product>
    <Copyright>Copyright © 2018-2025 TypeSW.com</Copyright>
    <Authors>TypeSW</Authors>
    <PackageId>HxCore.Standard</PackageId>
    <Description>.NET Standard 2.0 - Library</Description>
    <AssemblyVersion>1.4.29.0</AssemblyVersion>
    <FileVersion>1.4.29.0</FileVersion>
    <PackageProjectUrl>https://github.com/typesw/HxCore</PackageProjectUrl>
    <PackageLicenseUrl></PackageLicenseUrl>
    <RepositoryUrl>https://github.com/typesw/HxCore</RepositoryUrl>
    <Version>1.4.29</Version>
    <UserSecretsId>22e9bc6d-73be-4844-ad6b-9f757a8eb093</UserSecretsId>
    <SignAssembly>false</SignAssembly>
    <PackageReleaseNotes></PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;IDE0018;IDE0059;IDE0054;IDE0031</NoWarn>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\bin\Realse\</OutputPath>
    <NoWarn>1701;1702;IDE0018;IDE0059;IDE0054;IDE0031</NoWarn>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.1.34" />
    <PackageReference Include="MimeMapping" Version="3.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
    <PackageReference Include="System.Management" Version="6.0.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="&quot;E:\DevSpace\etc\Windows_Kits_bin\x86\signtool.exe&quot; sign /f &quot;E:\DevSpace\etc\인증서\CodeSign\chain\htenc.co.kr.pfx&quot; /p cimage1004@ /fd sha256 /v $(TargetPath)" />
  </Target>

</Project>
